FROM python:3.6

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pymysql
COPY . .
ENTRYPOINT ["celery", "-A", "pacifica.dispatcher.proxymod.__main__:celery_app", "worker"]
CMD ["--loglevel=info"]
