FROM python:3.6

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir uwsgi pymysql
COPY . .
EXPOSE 8069
ENTRYPOINT ["uwsgi", "--http-socket", "0.0.0.0:8069", "--master", "--die-on-term", "--wsgi-file", "/usr/src/app/pacifica/dispatcher/proxymod/__main__.py"]
